meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

SYNTH_STRATEGY: DELAY 4

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- big_logo

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y
CLOCK_PERIOD: 35 # 25 MHz

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.5
PL_RESIZER_SETUP_SLACK_MARGIN: 0.1
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.5
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.1

# Increase for more logic
# on your die
#PL_TARGET_DENSITY_PCT: 35
#GRT_ALLOW_CONGESTION: true

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 10
DRT_ANTENNA_MARGIN: 15 # %
DIODE_ON_PORTS: both

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75

# PDN - Core ring
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

# Since we cannot meet the minimum density limit on Metal2,
# ignore active metal on previous and subsequent layers
# (DM.5_DM.7 and DM.4_DM.6). Dummy metal is moved to active
# metal during the precheck.
KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  wrapped_vga:
    gds:
      - dir::../vga_screensaver/runs/latest/final/gds/wrapped_vga.gds
    lef:
      - dir::../vga_screensaver/runs/latest/final/lef/wrapped_vga.lef
    pnl:
      - dir::../vga_screensaver/runs/latest/final/pnl/wrapped_vga.pnl.v
    nl:
      - dir::../vga_screensaver/runs/latest/final/nl/wrapped_vga.nl.v
    spef:
      min_*: dir::../vga_screensaver/runs/latest/final/spef/min/wrapped_vga.min.spef
      nom_*: dir::../vga_screensaver/runs/latest/final/spef/nom/wrapped_vga.nom.spef
      max_*: dir::../vga_screensaver/runs/latest/final/spef/max/wrapped_vga.max.spef
    lib:
      max_ff_n40C_5v50: dir::../vga_screensaver/runs/latest/final/lib/max_ff_n40C_5v50/wrapped_vga__max_ff_n40C_5v50.lib
      max_ss_125C_4v50: dir::../vga_screensaver/runs/latest/final/lib/max_ss_125C_4v50/wrapped_vga__max_ss_125C_4v50.lib
      max_tt_025C_5v00: dir::../vga_screensaver/runs/latest/final/lib/max_tt_025C_5v00/wrapped_vga__max_tt_025C_5v00.lib
      min_ff_n40C_5v50: dir::../vga_screensaver/runs/latest/final/lib/min_ff_n40C_5v50/wrapped_vga__min_ff_n40C_5v50.lib
      min_ss_125C_4v50: dir::../vga_screensaver/runs/latest/final/lib/min_ss_125C_4v50/wrapped_vga__min_ss_125C_4v50.lib
      min_tt_025C_5v00: dir::../vga_screensaver/runs/latest/final/lib/min_tt_025C_5v00/wrapped_vga__min_tt_025C_5v00.lib
      nom_ff_n40C_5v50: dir::../vga_screensaver/runs/latest/final/lib/nom_ff_n40C_5v50/wrapped_vga__nom_ff_n40C_5v50.lib
      nom_ss_125C_4v50: dir::../vga_screensaver/runs/latest/final/lib/nom_ss_125C_4v50/wrapped_vga__nom_ss_125C_4v50.lib
      nom_tt_025C_5v00: dir::../vga_screensaver/runs/latest/final/lib/nom_tt_025C_5v00/wrapped_vga__nom_tt_025C_5v00.lib
    instances:
      wrapped_vga:
        location: [800, 605]
        orientation: N
    
  gf180mcu_ws_ip__id:
    gds:
      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
    instances:
      chip_id:
        location: [26, 26]
        orientation: N

  gf180mcu_ws_ip__logo:
    gds:
      - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
    instances:
      wafer_space_logo:
        location: ["expr::$DIE_AREA[2] + -169.25", "expr::$DIE_AREA[3] + -169.25"]
        orientation: N
        
  big_logo:
    gds:
      - dir::../big_logo/big_logo.gds
    lef:
      - dir::../big_logo/big_logo.lef
    vh:
      - dir::../big_logo/big_logo.v
    lib:
      "*":
        - dir::../big_logo/big_logo.lib
    instances:
      big_logo:
        location: [700, 1305]
        orientation: N

# Halo size around macros while cutting rows.
# Workaround for: https://github.com/The-OpenROAD-Project/OpenROAD/issues/8868
FP_MACRO_HORIZONTAL_HALO: 10
FP_MACRO_VERTICAL_HALO: 10
FP_PDN_HORIZONTAL_HALO: 5
FP_PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl

# Make sure netgen doesn't create 'no_connect' nets
# Not needed since netgen 1.5.303
LVS_FLATTEN_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- big_logo

# gf180mcu_ws_ip__id/logo has no ports and components
# therefore make it an abstract cell in the layout
MAGIC_EXT_ABSTRACT_CELLS:
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo
- big_logo

# Remove everything between this comment end the one below to disable use of the custom DFF cells
LIB:
  "*_tt_025C_5v00": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__tt_025C_5v00.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_ws_io__tt_025C_5v00.lib", "dir::../gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__tt_025C_5v00.lib"]
  "*_ss_125C_4v50": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__ss_125C_4v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_ws_io__ss_125C_4v50.lib", "dir::../gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__ss_125C_4v50.lib"]
  "*_ff_n40C_5v50": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__ff_n40C_5v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_ws_io__ff_n40C_5v50.lib", "dir::../gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__ff_n40C_5v50.lib"]
CELL_LEFS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lef/gf180mcu_fd_sc_mcu7t5v0.lef", "dir::../gf180mcu_as_ex_mcu7t5v0/lef/gf180mcu_as_ex_mcu7t5v0.lef"]
CELL_GDS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/gds/gf180mcu_fd_sc_mcu7t5v0.gds", "dir::../gf180mcu_as_ex_mcu7t5v0/gds/gf180mcu_as_ex_mcu7t5v0__dfxtp_2.gds"]
CELL_VERILOG_MODELS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/verilog/gf180mcu_fd_sc_mcu7t5v0.v", "pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/verilog/primitives.v", "dir::../gf180mcu_as_ex_mcu7t5v0/verilog/gf180mcu_as_ex_mcu7t5v0.v"]
CELL_SPICE_MODELS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/spice/gf180mcu_fd_sc_mcu7t5v0.spice", "dir::../gf180mcu_as_ex_mcu7t5v0/cds/gf180mcu_as_ex_mcu7t5v0.spice"]

EXTRA_EXCLUDED_CELLS: ["gf180mcu_fd_sc_mcu7t5v0__dff*", "gf180mcu_as_ex_mcu7t5v0__dy_*", "*_1"]
#End
